### ISSUE TITLE
Attribute ':wiki' not displayed

### ISSUE THREAD

**Issue by dan-zeman** [ufal/UMRGraphViz#2] opened 2023-11-20 13:29 UTC
In sentence 2 of [data/czech/mf020922_estonsko-DZ.txt](https://github.com/ufal/UMR/blob/main/data/czech/mf020922_estonsko-DZ.txt), _parlament_ has a `:wiki` attribute that is not shown.

<pre>
# :: snt2 Estonci volili parlament

(s2v / volit-001
    :wiki "Q372557"
    :ARG0 (s2p / person
        :mod (s2c / country
            :wiki "Q191"
            :name (s2n2 / name :op1 "Estonsko"))
        :refer-number plural)
    :ARG1 (s2p2 / parlament
        :wiki "Q217799"
        :refer-number singular)
    :aspect imperfective
    :modal-strength full-affirmative)
</pre>

![image](https://github.com/ufal/UMRGraphViz/assets/663752/1b5b75cb-166e-426f-ac18-c602adc8d8d6)

**Comment by michnov** [comment] 2023-11-23 11:52
This is caused by https://github.com/ufal/UMRGraphViz/blob/28b909e96e06a423a3b99f4d5d9bcfd788b49366/amrreader/src/reader.py#L78-L79 and it is actually inherited from the original AMR Reader (https://github.com/panx27/amr-reader/blob/d6161066c5b5c77ecf1a0347e70850e2a9814094/amrreader/src/reader.py#L85-L86).

The reason is that originally only named entities (concepts with the :name attribute visualized as blue squares) are allowed to contain a wiki link.

Do we want to change it that any concept can be linked to wiki data?
I can change it in a way that all concepts that contain the :wiki attribute would be considered a named entity.
The problem arises if we start assigning it also to events.

**Comment by dan-zeman** [comment] 2023-11-23 12:24
> The problem arises if we start assigning it also to events.

Really? If you look above, you'll see that, incidentally, this example also contains an event with the `:wiki` attribute. And here the visualizer shows it without complaints.

In general I think that it is useful to be able to use the `:wiki` attribute without a `:name` relation going from the same node. This clearly goes beyond the UMR guidelines (but so does our approach to use Wikidata instead of some ill-defined "article title").

<pre>
   if role == ':wiki': 
       continue 
</pre>

Regardless of how our guidelines differ from the official ones, I don't think it's a good idea for the visualizer to skip a particular attribute at a particular place. It is a visualizer of the data, so it should show anything that is in the data, as long as the data can be parsed.

**Comment by michnov** [comment] 2023-11-23 13:44
> Regardless of how our guidelines differ from the official ones, I don't think it's a good idea for the visualizer to skip a particular attribute at a particular place. It is a visualizer of the data, so it should show anything that is in the data, as long as the data can be parsed.

Definitely! I completely agree and I'll fix it. Thank you!

> > The problem arises if we start assigning it also to events.
> 
> Really? If you look above, you'll see that, incidentally, this example also contains an event with the `:wiki` attribute. And here the visualizer shows it without complaints.

My bad, I didn't explain it well. I wasn't worried about showing the :wiki attribute causing trouble. What I was unsure about was my own idea to make every concept with the :wiki attribute appear as a named entity (that is, displaying it as a blue rectangle). But looking at the example, where 3 out of 4 boxes would be "named entities" and the predicate wouldn't be clearly distinguishable, I'm thinking it might not be such a great idea. Definitely not for events.

**Comment by michnov** [comment] 2023-11-23 20:35
The bug fixed.

It should now display the value of the :wiki attribute for all nodes, no matter of its type.
Moreover, if the value is recognized as a WikiData ID, its English title is automatically retrieved.

![image](https://github.com/ufal/UMRGraphViz/assets/11574860/f28d3010-a8ca-46db-b3f9-6ac9d3e7cc6f)

**Comment by dan-zeman** [comment] 2023-11-23 20:51
Thanks, showing the Wikidata title is a cool idea! However, I am now unable to load [mf020922_estonsko-DZ.txt](https://github.com/ufal/UMR/blob/main/data/czech/mf020922_estonsko-DZ.txt), it throws an exception:

<pre>
Saving mf020922_estonsko-DZ.txt to mf020922_estonsko-DZ.txt
2023-11-23 20:44:37,401: INFO: processing mf020922_estonsko-DZ.txt
Traceback (most recent call last):
  File "/content/UMRGraphViz/amrreader/main.py", line 50, in <module>
    sents = reader.main(raw_amrs)
  File "/content/UMRGraphViz/amrreader/src/reader.py", line 363, in main
    amr_nodes_acronym, path = amr_reader(sent_umr)
  File "/content/UMRGraphViz/amrreader/src/reader.py", line 307, in amr_reader
    generate_nodes_multiple(i, amr_nodes_content, amr_nodes_acronym)
  File "/content/UMRGraphViz/amrreader/src/reader.py", line 219, in generate_nodes_multiple
    assert(is_named_entity != bool(arg_nodes))
AssertionError
</pre>

**Comment by michnov** [comment] 2023-11-23 22:33
Sorry, I forgot to check it on the full document, not just the sentence with the issue. Should be ok now. However, it may still crash on some files due to #3

**Closed as completed by michnov** 2023-11-23 22:33 UTC
Labels: bug
